# custom_cursor_colors = true
live_config_reload = true

# [bell]
# animation = "EaseOutExpo"
# color = "#fbf1c7"
# duration = 0

# [colors]
# draw_bold_text_with_bright_colors = true
#
# [colors.search]
# matches = { foreground = '#b2b2b2', background = '#b26818' }
# focused_match = { foreground = "CellBackground", background = "CellForeground" }

# Colors (SeaShells)
# Source  https//raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/SeaShells.itermcolors

######## Fluoromachine #  Florest #########
# Default colors
# [colors.primary]
# background = '#262335' # '#1c1917'
# foreground = '#8BA7A7' # '#ebdbb2' '#e5c49e'

# [colors.cursor]
# text = '#fbf1c7'
# cursor = '#feaf3c'

# [colors.selection]
# text = '#FFCC00'       # '#7A7164' # '#ffe9d7'
# background = '#242728'

# # Normal colors
# [colors.normal]
# black = '#181A1B'
# red = '#cc241d'
# green = '#72F1B8'   # '#98971a'
# yellow = '#FFCC00'  # '#d79921'
# blue = '#290CFF'    # #458588'
# magenta = '#FC199A' # '#AF6DF9' # '#b16286'
# cyan = '#61E2FF'    # '#689d6a'
# white = '#fbf1c7'   # '#a89984' '#BDB7AF'
#
# # Bright colors
# [colors.bright]
# black = '#928374'
# red = '#fb4934'
# green = '#b8bb26'
# yellow = '#FFCC00'  #'#fabd2f'
# blue = '#83a598'
# magenta = '#d3869b'
# cyan = '#8ec07c'
# white = '#ebdbb2'

# [colors.dim]
# black = '#000000'
# red = '#FC199A'     # '#b21818'
# green = '#18b218'
# yellow = '#FFCC00'  # '#b26818'
# blue = '#458588'
# magenta = '#b218b2'
# cyan = '#18b2b2'
# white = '#b2b2b2'

##### GRAY #####
# [colors.normal]
# black = '#1a1a1a'
# red = '#fb4934'
# green = '#cccccc'
# yellow = '#a1a1a1'
# blue = '#a8a8a8'
# magenta = '#b3b3b3'
# cyan = '#c0c0c0'
# white = '#d9d9d9'
#
# # Bright colors
# [colors.bright]
# black = '#000000'
# red = '#808080'
# green = '#8a8a8a'
# yellow = '#9c9c9c'
# blue = '#acacac'
# magenta = '#bdbdbd'
# cyan = '#cccccc'
# white = '#f0f0f0'
#
# [colors.dim]
# black = '#181A1B'
# red = '#4f4f4f'
# green = '#606060'
# yellow = '#707070'
# blue = '#808080'
# magenta = '#8f8f8f'
# cyan = '#9e9e9e'
# white = '#cccccc'

##### GREEN #####
# [colors.normal]
# black = '#1a1a18'
# red = '#fb4934'
# yellow = '#9ba589'
# blue = '#96a399'
# magenta = '#97a49c'
# cyan = '#b5c2af'
# white = '#cbd2c4'

# Bright colors
# [colors.bright]
# black = '#0f130f'
# red = '#687f6f'
# yellow = '#bac0a3'
# blue = '#c6d1bc'
# magenta = '#d1dbcb'
# cyan = '#dfe4d9'
# white = '#f0f7ea'

# [colors.dim]
# black = '#141715'
# red = '#3f574e'
# yellow = '#838d7d'
# blue = '#8d9a89'
# magenta = '#9ba399'
# cyan = '#b3bfb1'
# white = '#c7cfc4'


[cursor]
style = "Block"
unfocused_hollow = true

[debug]
persistent_logging = false
render_timer = false

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Light Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Control"

# [[keyboard.bindings]]
# action = "ClearSelection"
# key = "C"
# mods = "Alt|Shift"
# chars = "\u000ff"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Alt"

# ScrollPageUp
# ScrollPageDown
# ScrollLineUp
# ScrollLineDown
# ScrollToTop
# ScrollToBottom

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Minus"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;5~"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[2~"
key = "Insert"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002o"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002;"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002/"
key = "F"
mods = "Command"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 3000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.95
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 36

[window.padding]
x = 5
y = 5
